### PR TITLE
Sync with RPi-Distro repos, add Pi 400 firmwares

### PR DESCRIPTION
**Pull request by HiassofT**

### CODE REVIEW

**Review by chewitt — APPROVED** [review]

**Comment by mikaku** [comment]
Hello,

I realized that in this PR the file `firmware/brcm/brcmfmac43430-sdio.clm_blob` was removed and is no longer available.
Any idea if this is a mistake?

Thanks.

**Comment by HiassofT** [comment]
The removal was intentional, the file not present in the RPi distro either: https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/tree/master/firmware/brcm

It only existed there for a very short time, it was added in commit https://github.com/RPi-Distro/firmware-nonfree/commit/4ee44af381d55bc2221cf80c1433842a48ed09e1 and removed again in commit https://github.com/RPi-Distro/firmware-nonfree/commit/00daf85ffa373ecce7836df7543c6ebe4cf43639 - and it seems we missed to remove it in our repo back then

**Comment by mikaku** [comment]
I see, I guess this file is probably auto-generated during the firmware installation.
Thanks.

**Comment by chewitt** [comment]
See https://patchwork.kernel.org/project/linux-wireless/patch/20210607103433.21022-1-matthias.bgg@kernel.org/ the CLM blob is optional, but tends to be used with devices destined for a specific country/region to optimise wireless properties for a specific market. As LE and RPiOS are somewhat global in nature they can't be that specific and shouldn't use them.

**Comment by mikaku** [comment]
Ah, that clears me up some things.
Thank you very much guys, and sorry for the noise.

**Pull request merged**
